### ISSUE TITLE
RTP processed spectra data saved in wrong place

### ISSUE THREAD

**Issue by twVolc** [volcanotech-sw/PyCamPermanent#164]
From your RTP branch @ubdbra001 

The processed spectra folder is currently put into the current `spec_dir` rather than the current `watching_dir`. This should be moved to adding the processed data to the `watching_dir` as the user may have the `spec_dir` set up for processig of some old spectra (or as we just tried, just having the default test spectra loaded) and then the processed data of the new `watching_dir` is put somewhere unexpected.

**Comment by ubdbra001** [comment]
Yep, this is fixed on my local version, but I haven't pushed those changes yet.

**Comment by tpering** [comment]
This also links with issue #177
