### ISSUE TITLE
Error with real-time processing 

### ISSUE THREAD

**Issue by tpering** [volcanotech-sw/PyCamPermanent#52]
The below error appears when trying to process data as it is coming into a folder, when display only mode isn't ticked
![image](https://github.com/twVolc/PyCamPermanent/assets/7857899/77ca543a-1f73-4bab-b0ca-214bb57e4c75)

**Comment by ubdbra001** [comment]
Stumbled across this today, looks like an issue with `full_df = pd.merge_asof(tau_df, fit_df, "timepoint")` in the `save_calibration` function of `PyplisWorker`. It happened when I selected __"display only mode"__ from the Processing Menu with no data loaded. In this case it looks like it is trying to merge two empty dataframes (`tau_df` and `fit_df`).

**Comment by tpering** [comment]
@ubdbra001 does #143 fix this too?

**Comment by ubdbra001** [comment]
Yes, I think so
