### ISSUE TITLE
Potential dead code that could be removed

### ISSUE THREAD

**Issue by ubdbra001** [volcanotech-sw/PyCamPermanent#97]
Just collecting instances of code that look to be unused, and could potentially be removed.

**Comment by ubdbra001** [comment]
I think this section may be superceded by the `save_calibration()` function?

https://github.com/twVolc/PyCamPermanent/blob/65e87a45b12c0493712c249e46eb48bb03aaa4ed/pycam/so2_camera_processor.py#L2283-L2296

**Comment by ubdbra001** [comment]
I think all the info recorded in `processing_settings.txt` is now either in the config or save in other files with the config?

https://github.com/twVolc/PyCamPermanent/blob/65e87a45b12c0493712c249e46eb48bb03aaa4ed/pycam/so2_camera_processor.py#L3855-L3867

**Comment by twVolc** [comment]
Yep, I'm pretty sure both are redundant now!
